[dados] br_me_comex_stat
basedosdados/queries pull request #46
Opened 2023-05-09 14:11 UTC by folhesgabriel

- Register prod `dbt models` for `br_me_comex_stat`: 
- `municipio_importacao`
- `municipio_exportacao`
- `ncm_importacao`
- `ncm_exportacao`

2023-05-09 19:36 UTC, crislanealves approved these changes
1. @folhesgabriel vou deixar aprovado, mas confirma com o @lucascr91 e @mfagundes se foi resolvido a questão do particionamento. Antes, a tabela ser particionada no storage não implicava - nem deveria - que a tabela estaria particionada no processo de materialização. 
Caso ainda seja a mesma lógica, é só copiar o exemplo da PNAD e adaptar para essa e todas as tabelas que precisam de particionamento nas pipelines. 
[br_ibge_pnadc.microdados](https://github.com/basedosdados/queries-basedosdados/blob/master/models/br_ibge_pnadc/br_ibge_pnadc__microdados.sql)

2. **[off topic] - cc:** @mfagundes e @lucascr91 

Ainda acho que o schedule das tabela não deveria ser mensal, visto quase nunca é possível saber quando os dados estarão disponíveis na origem.

2023-05-10 00:34 UTC, mfagundes commented
> 1. @folhesgabriel vou deixar aprovado, mas confirma com o @lucascr91 e @mfagundes se foi resolvido a questão do particionamento. Antes, a tabela ser particionada no storage não implicava - nem deveria - que a tabela estaria particionada no processo de materialização.
>    Caso ainda seja a mesma lógica, é só copiar o exemplo da PNAD e adaptar para essa e todas as tabelas que precisam de particionamento nas pipelines.
>    [br_ibge_pnadc.microdados](https://github.com/basedosdados/queries-basedosdados/blob/master/models/br_ibge_pnadc/br_ibge_pnadc__microdados.sql)
> 2. **[off topic] - cc:** @mfagundes e @lucascr91
> 
> Ainda acho que o schedule das tabela não deveria ser mensal, visto quase nunca é possível saber quando os dados estarão disponíveis na origem.

Esta é uma tabela bem grande e precisamos particionar e fazer atualizações incrementais. Quanto à questão do schedule, deixei os comentários no próprio arquivo. Mesmo quando queremos que rode em um determinado dia do mês, devemos usar o `CronClock`. O intervalo de 30 dias gera uma grande diferença em pouco tempo.

2023-05-21 19:37 UTC, crislanealves requested changes

2023-05-21 19:37 UTC, crislanealves commented on models/br_me_comex_stat/municipio_exportacao.sql
> +    cluster_by = ["mes", "sigla_uf", "id_municipio"],
Chegou a testar a performance com `id_municipio`? Não sei se será é uma variável muito utilizada na consulta. Testaria a performance com e sem `id_municipio` em dev antes de colocar em produção.

2023-05-22 14:25 UTC, lucascr91 approved these changes

2023-05-23 16:54 UTC, lucascr91 approved these changes

2023-05-23 16:54 UTC, merged